### ISSUE TITLE
incomplete description for NamingConventions::Capitalization?

### ISSUE THREAD

**Issue by garu** [moznion/Perl-Lint#70]
Hello! I created a package called "app::User" and, after passing Perl::Lint, all I got was this:

    {
        description   "app",
        explanation   [
            [0] 45,
            [1] 46
        ],
        filename      "Projects/app/lib/app/User.pm",
        line          1,
        policy        "Perl::Lint::Policy::NamingConventions::Capitalization"
    }

I understood from the description that "app" was the violation, but all the other descriptions I got were more verbose, so I think it should say something like "package name "app::User" should be capitalized" or something like that.

What do you think?

**Comment by moznion** [comment]
Thank you for reporting. Fixed!
